services:
  backend:
    build:
      context: ../biblioteca-digital-backend
      dockerfile: Dockerfile
    volumes:
      - ../biblioteca-digital-backend/libros_pdf:/app/libros_pdf
      - ../biblioteca-digital-backend/libros_portada:/app/libros_portada
      - ../biblioteca-digital-backend/wallet:/app/wallet
    env_file:
      - ../biblioteca-digital-backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ../biblioteca-digital-frontend
    ports:
      - "80:80"
    volumes:
      - ../biblioteca-digital-backend/libros_pdf:/var/www/libros_pdf
      - ../biblioteca-digital-backend/libros_portada:/var/www/libros_portada
    depends_on:
      - backend
    restart: unless-stopped
